### ISSUE TITLE
Allow value objects in fromArray

### ISSUE THREAD

**Issue by codeliner** [event-engine/php-data#13]
With a small change it would be possible to support value objects in `fromArray` factory method.

[This line](https://github.com/event-engine/php-data/blob/master/src/ImmutableRecordLogic.php#L184) in ImmutableRecordLogic needs to be changed to:

`$recordData[$key] = $this->fromType($this->voTypeToNative($val, $key, $type), $type);`

- [ ] Check if it works like expected
- [ ] Add unit tests for it
- [ ] Add doc block comments to fromArray  and fromRecordData to explain difference *

_*) Difference: fromRecordData avoids mapping values to native data and back to VO. So it is more performant. On the other hand, fromArray can be used as a universal factory, which makes handling much simpler._

**Comment by ahmed-alaa** [comment]
@codeliner I checked it and not as we thought initially.

in `setNativeData`, the [switch](https://github.com/event-engine/php-data/blob/master/src/ImmutableRecordLogic.php#L167) checks against the `type` which could be string, int or value object.

The `value` is the tricky part and contains multiple scenarios:
1. It can be "test", 0
```
::fromArray([
    'name' => 'Test',
]);
```

2. It can be value object
```
::fromArray([
    'name' => namespace\ValueObjects\Name,
]);
```

Using method `voTypeToNative` with case 1 -> will throw an exception
Using directly method `fromType` with case 2 -> will throw an exception

It could be solved inside the switch statement to check the type of the value as well but will come with complexity/code smell, I believe.

What do you think?

**Comment by codeliner** [comment]
Ah, of course it is not that easy. :thinking: I really liked the idea to support VOs directly in `fromArray` but I think you're right, it would increase complexity and ImmutableRecord is already complex enough. I'm closing the issue. We should keep it as-is.
