### ISSUE TITLE
Introduce ImmutableRecordLogicNative which only uses fromNative and toNative methods

### ISSUE THREAD

**Issue by sandrokeil** [event-engine/php-data#17]
Instead of checking the type of a value to determine the method call for the correct value object method e.g. `fromInt()`, `fromString()` ... we should create a new immutable record trait which only relies on the methods `fromNative()` and `toNative()`. This would also reduce the complexity of the trait and increases the performance as well.

For example [these methods](https://github.com/event-engine/php-data/blob/master/src/ImmutableRecordLogic.php#L349-L398) are not needed anymore.

**Comment by codeliner** [comment]
`fromNative` and `toNative` are not type safe. You would need to add assertions everywhere. This option was considered long ago but not used because of that reason.

**Comment by sandrokeil** [comment]
That‘s right. We can use an union type and type safety only on the class property level, but I guess it‘s not working well. Especially for the return type of `toNative`.
