### ISSUE TITLE
Add support for DateTimeInterface

### ISSUE THREAD

**Issue by brunowowk** [event-engine/php-data#4]
When using a `DateTimeInterface` property we get:

```
Cannot convert property dateTimeProperty to its native counterpart. Missing to{nativeType}() method in the type class DateTimeInterface.
```

**Comment by codeliner** [comment]
Hey @brunowowk , sorry for answering late. Did not find enough time last weeks to check my Github stream.

Only `DateTimeImmutable` is supported, because `DateTimeInterface` does not guarantee immutability. Usage is demonstrated in the docs: https://event-engine.io/api/immutable_state.html#3-4-3-2

**Comment by brunowowk** [comment]
> Hey @brunowowk , sorry for answering late. Did not find enough time last weeks to check my Github stream.

No problem at all, thank you for taking the time to answer

> Only `DateTimeImmutable` is supported, because `DateTimeInterface` does not guarantee immutability. Usage is demonstrated in the docs: https://event-engine.io/api/immutable_state.html#3-4-3-2

Makes perfect sense, sorry for the oversight. I'm closing this.
