### ISSUE TITLE
Use method return type as fallback in 2.x 

### ISSUE THREAD

**Issue by codeliner** [event-engine/php-data#7]
@arnedesmedt I had to change your PHP 7.4 implementation a bit, due to `ReflectionType::__toString()` being deprecated. See #6 
I also added the exception back. Now it's thrown when the property has no type hint. However, we could also use the old logic (method return type) as a fallback in case no property type hint is given.
This would ease the migration path from 1.x to 2.x because you don't have to change all your ImmutableRecords at once. What do you think? Can you provide a PR for it and maybe also add some test cases?

**Comment by codeliner** [comment]
Inspiration for tests can be found here: https://github.com/event-engine/php-json-schema/pull/7/files

**Comment by arnedesmedt** [comment]
Oh, I forgot the deprecation of __toString(), sorry for that. I will add the fallback logic in a separate PR, with some tests.

**Comment by arnedesmedt** [comment]
I've added a PR: https://github.com/event-engine/php-data/pull/8
